package com.bitmax.digidial.navigation

sealed class Route(val route: String) {
    object Splash : Route("Splash")
    object Login : Route("login")
    object EditProfile : Route("editprofile")
    object HomeScreen : Route("homeScreen/{phoneNumber}")
    object Call : Route("call")
    object CallRecording : Route("callrecording")
    object Recording : Route("recording")
    object HelpAndSupport : Route("helpandsupport")
    object Dashboard : Route("dashboard")
    object MyProfile : Route("myprofile")
    object NewNote : Route("new_note")
    object MeetingNotes : Route("meeting_notes")
    object Reports : Route("reports")
    object ClientProposal : Route("client_proposal")
    object SwitchAccount : Route("switch_account")
    object AgentDashboard : Route("agentdashboard")
    object ViewPlan : Route("viewplan")
    object AddTeamMembers : Route("addteammembers")
    object OtpVerification : Route("otpverification/{phoneNumber}")
    object GrantPermission : Route("grantpermission")
    object ContactDetails : Route("contactDetails")
}
